### ISSUE TITLE
Undefined method `WC_Admin_Order::get_customer_first_name()`

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#2688]
**Describe the bug**
From a stack trace on woocommerce.com:

```
[22-Jul-2019 23:12:40 UTC] Fatal error: Uncaught Error: Call to undefined method WC_Admin_Order::get_customer_first_name() in /var/www/wp-content/plugins/woocommerce-admin/includes/data-stores/class-wc-admin-reports-customers-data-store.php:627
Stack trace:
#0 /var/www/wp-includes/class-wp-hook.php(286): WC_Admin_Reports_Customers_Data_Store::update_registered_customer(662052)
#1 /var/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /var/www/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /var/www/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store.php(212): do_action('woocommerce_upd...', 662052)
#4 /var/www/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(179): WC_Customer_Data_Store->update(Object(WC_Customer))
#5 /var/www/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php(208): WC_Data_Store->update(Object(WC_Customer))
#6 /var/www/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1039): WC_Data->save()
#7 /var/www/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1108): WC_Checkout->process_customer(Array)
#8 /var/www/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(462): WC_Checkout->process_checkout()
#9 /var/www/wp-includes/class-wp-hook.php(286): WC_AJAX::checkout('')
#10 /var/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#11 /var/www/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#12 /var/www/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(87): do_action('wc_ajax_checkou...')
#13 /var/www/wp-includes/class-wp-hook.php(286): WC_AJAX::do_wc_ajax('')
#14 /var/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(false, Array)
#15 /var/www/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#16 /var/www/wp-includes/template-loader.php(13): do_action('template_redire...')
#17 /var/www/wp-blog-header.php(19): require_once('/var/www/wp-inc...')
#18 /var/www/index.php(17): require('/var/www/wp-blo...')
```

**To Reproduce**
Seeing if I can get a reproducible flow.

**Comment by timmyc** [comment]
Appears the logic here was added/refactored in https://github.com/woocommerce/woocommerce-admin/pull/2418
