### ISSUE TITLE
Add defensive type-checking for Reports Controller `get_order_number`

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-admin#4447]
**Describe the bug**

Today while testing how the new draft order status introduced by WooCommerce Blocks 2.6.0 appears in the WC-Admin order list table (as a part of some documentation I'm writing for Woo Happiness), the order network request returned a 500:

<img width="1712" alt="Image 2020-05-26 at 7 48 56 PM" src="https://user-images.githubusercontent.com/1429108/82962673-da02a400-9f8e-11ea-9006-8026e4bdfad0.png">

The stack trace was:

```
[26-May-2020 23:41:47 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_type() on boolean in /srv/www/woo/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/Controller.php:188
Stack trace:
#0 /srv/www/woo/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/Orders/Controller.php(85): Automattic\WooCommerce\Admin\API\Reports\Controller->get_order_number(1149)
#1 /srv/www/woo/public_html/wp-includes/rest-api/class-wp-rest-server.php(1015): Automattic\WooCommerce\Admin\API\Reports\Orders\Controller->get_items(Object(WP_REST_Request))
#2 /srv/www/woo/public_html/wp-includes/rest-api/class-wp-rest-server.php(342): WP_REST_Server->dispatch(Object(WP_REST_Request))
#3 /srv/www/woo/public_html/wp-includes/rest-api.php(306): WP_REST_Server->serve_request('/wc-analytics/r...')
#4 /srv/www/woo/public_html/wp-includes/class-wp-hook.php(287): rest_api_loaded(Object(WP))
#5 /srv/www/woo/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#6 /srv/www/ in /srv/www/woo/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/Controller.php on line 188
```

The code producing the error is:

https://github.com/woocommerce/woocommerce-admin/blob/714660f67ee03ba94bc0febf30d2acbfe22bca7d/src/API/Reports/Controller.php#L185-L197

When troubleshooting the state of order number `1149` in my database, I noticed that it does not exist in the my db's `wp_post` table but it _does_ exist in the `wc_order_stats` table. So this is why the fatal is happening. As for why it doesn't exist in the `wp_post` table, a further clue is that the order status as indicated in the `wc_order_stats` table is `wc-checkout-draft`. So, some back story:

In WooCommerce 2.6.0 we introduced the `wc-checkout-draft` status for Woo orders because we now create them whenever the checkout is started via the checkout block. This is so that we can track various changes to the order via the new Store endpoint for orders during the checkout process. Effectively "draft" orders just mean that the checkout has been started by a shopper but has not been submitted yet. At the point of submission the normal statuses are applied to the order for its lifetime.

However, if a shopper _abandons_ checkout without submitting, the order stays in the database until it is cleaned up (deleted) by a scheduled action scheduler task every 24 hours:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/4de7cf163deef5168b053b050ddf35430e64c03e/src/Library.php#L133-L147

What we didn't anticipate, is that there may be plugins (like wc-admin) that have custom tables synced with the main table for orders that will not know that the orders have been deleted.

I'm still not sure long term what should happen here (I've created a corresponding issue in the blocks repo (https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2570), but for the short term, I've confirmed that if some defensive type checking is done in this method, it fixes things:

```php
public function get_order_number( $order_id ) {
	$order = wc_get_order( $order_id );

	if ( ! $order instanceof \WC_Order ) {
		return '';
	}

	if ( 'shop_order_refund' === $order->get_type() ) {
		$order = wc_get_order( $order->get_parent_id() );
	}

	if ( ! has_filter( 'woocommerce_order_number' ) ) {
		return $order->get_id();
	}

	return $order->get_order_number();
}
```

Result:

<img width="1385" alt="Image 2020-05-26 at 8 14 31 PM" src="https://user-images.githubusercontent.com/1429108/82963287-6e213b00-9f90-11ea-8a4d-b6301e916c2b.png">

On our end, we're going to have to implement a fix as well because this issue will surface on older versions of WooCommerce with blocks and WC-Admin (either in core or as a plugin) active but I _do_ think there still should be some defensive type checks in this code to prevent a site from bricking when there is no order for a given id. Probably worth a review to ensure anywhere else an id (or other lookup value) comes from the `wc_order_stats` table is used for retrieving an order (or other data) that there's checks to make sure the expected data exists as well.

**To Reproduce**

1. Activate [WooCommerce blocks 2.6.0](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/4678919/woocommerce-gutenberg-products-block.zip) (link to zip).
2. Add the checkout block to a page.
3. Add some products to your cart and visit the page with the checkout block.
4. I don't know when new orders are added to the `wc_stats_table` but however that happens, make sure the new draft order is in the table.
5. (to speed things up) manually delete the draft order from your database.
6. Visit the WC-Admin order list table route and you'll see the 500 on the network response.

Alternatively, if you don't mind potentially borking something else, you can just delete any order from the `wp_post` table and it will produce the fatal (if that order also exists in the `wc_order_stats` table.

**Comment by nerrad** [comment]
Note I subsequently realized that Woo-Admin hooks into `delete_post` that should pick up when orders are deleted and sync those deletes with the `wc_order_stats` table. So that's 💯 for keeping things in sync. However, I still think anywhere an order is retrieved, there should be some explicit checking to validate the order actually exists because it is entirely possible via migrations gone bad, or scenarios where an extension directly deletes orders results in `wc_order_stats` getting out of sync with the `wp_posts` table.
