### ISSUE TITLE
Console errors in JS tests

### ISSUE THREAD

**Issue by octaedro** [woocommerce/woocommerce-admin#6473]
**Describe the bug**
As a follow-up to [this PR](https://github.com/woocommerce/woocommerce-admin/pull/6472), there are a couple of console errors related to these tests:
`client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js`

**Errors**
```
 console.error
    Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React.

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:5)
      at Object.unmountComponentAtNode (node_modules/react-dom/cjs/react-dom.development.js:24878:9)
      at node_modules/@testing-library/react/dist/pure.js:142:23
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:21856:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
      at cleanupAtContainer (node_modules/@testing-library/react/dist/pure.js:141:26)

  console.error
    Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React.

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:5)
      at Object.unmountComponentAtNode (node_modules/react-dom/cjs/react-dom.development.js:24878:9)
      at node_modules/@testing-library/react/dist/pure.js:142:23
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:21856:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
      at cleanupAtContainer (node_modules/@testing-library/react/dist/pure.js:141:26)
```

**To Reproduce**

1. Run in the console `npm run test client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/test/index.js`
2. The console errors should be visible.

**Expected behavior**
The tests shouldn't throw console errors.

**Screenshots**
<img width="899" alt="Captura de Pantalla 2021-03-01 a la(s) 11 06 58" src="https://user-images.githubusercontent.com/1314156/109510187-79a21500-7a80-11eb-91f0-aa0ab537bce7.png">

**Desktop (please complete the following information):**
* OS: Mac OS

**Comment by samueljseay** [comment]
I also see a lot of warnings about deprecated APIs that we could address as part of this:

```
console.warn
    wp.compose.withGlobalEvents is deprecated. Please use useEffect instead.

      at console.<anonymous> (node_modules/jest-environment-jsdom-sixteen/node_modules/jest-mock/build/index.js:814:25)
      at deprecated (node_modules/@wordpress/deprecated/build/@wordpress/deprecated/src/index.js:73:10)```

**Comment by ilyasfoo** [comment]
>I also see a lot of warnings about deprecated APIs that we could address as part of this:

Unfortunately, that warning seems to come from `@wordpress/components` in the latest 11.* version branch which still [uses the deprecated function](https://github.com/WordPress/gutenberg/blob/%40wordpress/components%4011.1.5/packages/components/src/focusable-iframe/index.js#L10). I think upgrading to 12 would have breaking changes, so I wouldn't spend time on this one yet

**Comment by chihsuan** [comment]
> Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React.

It seems that we [create some new elements in our component using `document` APIs](https://github.com/woocommerce/woocommerce-admin/blob/main/client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/index.js#L201-L203). The React warns us because they are not rendered by this React instance.

We can probably fix this by mocking the document object but this is expected for the currently implemented tests. 

**I'm closing this since this is a bug for over 6 months old and I think it's not worth fixing this.** Please feel free to reopen this if having other thoughts.
