### ISSUE TITLE
@woocommerce/components dependency breaks tests for external plugins

### ISSUE THREAD

**Issue by tomalec** [woocommerce/woocommerce-admin#6483]
## **Describe the bug**

I'm writing a plugin the depends on `@woocommerce/components`, and testing it using `wp-scripts`.
When any of my test files imports (directly or indirectly) `@woocommerce/components` tests fail with:
```
Jest encountered an unexpected token
...
    Details:

    /home/tomalec/repos/wc-com-test/node_modules/@woocommerce/components/build/index.js:4
    import 'react-dates/initialize'; // The above: Turn on react-dates classes/styles, see https://github.com/airbnb/react-dates#initialize
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

I tried tweaking with `transformIgnorePatterns`, but that resulted in even stranger:
```
    Cannot find module '@wordpress/url' from 'index.js'

    Require stack:
      node_modules/@woocommerce/components/node_modules/@woocommerce/navigation/build/index.js
      node_modules/@woocommerce/components/build/advanced-filters/index.js
      node_modules/@woocommerce/components/build/index.js
      js/src/test/fails.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:299:11)
      at Object.<anonymous> (../../../../Users/psealock/vagrant-local/www/tangaroa/public_html/wp-content/plugins/wc-admin/packages/navigation/src/index.js:4:1)

Test Suites: 1 failed, 1 passed, 2 total
```
or
```
    TypeError: Cannot read property 'add' of undefined

      at setupWPTimezone (node_modules/@woocommerce/components/node_modules/@wordpress/date/build/@wordpress/date/src/index.js:141:15)
      at Object.<anonymous> (node_modules/@woocommerce/components/node_modules/@wordpress/date/build/@wordpress/date/src/index.js:527:1)
      at Object.<anonymous> (../../../../Users/psealock/vagrant-local/www/tangaroa/public_html/wp-content/plugins/wc-admin/packages/components/src/date/index.js:5:1)
      at Object.<anonymous> (../../../../Users/psealock/vagrant-local/www/tangaroa/public_html/wp-content/plugins/wc-admin/packages/components/src/index.js:14:1)
      at Object.<anonymous> (js/src/setup-mc/top-bar/index.js:4:1)
      at Object.<anonymous> (js/src/setup-mc/index.js:4:1)
      at Object.<anonymous> (js/src/setup-mc/test/index.js:9:1)
```

## **To Reproduce**

1. Set up a repo that uses `@wordpress/scripts` and `@woocommerce/components`
2. Write a test that uses `@woocommerce/components`
	```js
	import foo from '@woocommerce/components';

	describe( 'Dependencies', () => {
		test( 'should not break tests', () => {
			expect( true ).toEqual( true );
		   } );
	} );
	```
3. Run the tests: `wp-scripts test-unit-js`

## **Expected behavior**
The test should run and pass

## **Screenshots**
![image](https://user-images.githubusercontent.com/17435/109677992-7c813080-7b7a-11eb-89b5-8ed25b01c8b6.png)

<details>
<summary>Full log</summary>
<pre><code>
> wp-scripts test-unit-js

 PASS  js/src/test/works.js
  Dependencies
    ✓ should not break tests (3ms)

 FAIL  js/src/test/fails.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/tomalec/repos/wc-com-test/node_modules/@woocommerce/components/build/index.js:4
    import 'react-dates/initialize'; // The above: Turn on react-dates classes/styles, see https://github.com/airbnb/react-dates#initialize
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | // Any of this breaks
    > 2 | import foo from '@woocommerce/components';
        | ^
      3 |
      4 | describe( 'Dependencies', () => {
      5 | 	test( 'should not break tests', () => {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1258:14)
      at Object.<anonymous> (js/src/test/fails.js:2:1)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.355s
Ran all test suites.

</code></pre>

</details>

## **Additional context**

The `transformIgnorePatterns` tweak I tried:
```js
const defaultConfig = require( '@wordpress/scripts/config/jest-unit.config' );

module.exports = {
	...defaultConfig,
	// That does not help either
	transformIgnorePatterns: [ ...(defaultConfig.transformIgnorePatterns || []), 'node_modules/(?!@woocommerce)' ],
};

```

**Comment by psealock** [comment]
I can reproduce this using a new project created via `npm run create-wc-extension`.

```js
/**
 * External dependencies
 */
import { Card } from '@woocommerce/components';  // Doesn't work
import { Card } from '@wordpress/components'; // Works 🤷🏽 

describe( 'Dependencies', () => {
	test( 'should not break tests', () => {
		expect( Card ).toBeDefined();
	} );
} );
```
Note that `@wordpress/components` does work. Looking at the output files in `node_modules`, both dependencies have `import` statements, so I'm not too sure whats happening.

**Comment by psealock** [comment]
Estimate: 2. Its probably lots of digging around followed by a one line fix.

**Comment by tomalec** [comment]
> Looking at the output files in node_modules, both dependencies have import statements, so I'm not too sure whats happening.

When I was debugging it being run by jest (`--inspect-brk`), at some point the `wordpress/data` (IIRC) was being imported from a built version that was transpired to legacy syntax and I suspect something was wrong around default export. That's nothing sure mostly my suspicions, hopefully could give any value to someone.

In general, I wonder why do we transpile it back and forth. It would be nice to run plain ES modules in the environments that support it - like node or chrome, it would make debugging tests so much easier.

**Comment by tomalec** [comment]
FWIW, 
`import { getDateParamsFromQuery } from '@woocommerce/date';`
Also doesn't work.

**Comment by tomalec** [comment]
FWIW, transforming `@woocommerce/date/build/index.js` helped to workaround the problem with `@woocommerce/date` and `@woocommerce/components`:

```js
transformIgnorePatterns: [ 'node_modules/(?!@woocommerce/date/build)' ],
transform: {
	  ...( defaultConfig.transform || [] ),
	  'node_modules/@woocommerce/date/build/index.js': 'babel-jest',
},
```

**Comment by tomalec** [comment]
It seems there are two separate versions of `@wordpress/date` being used for some reason:
![image](https://user-images.githubusercontent.com/17435/118670685-1e69fe00-b7f7-11eb-9cdf-f317ae2db050.png)
Maybe there is a mismatch between them

**Comment by tomalec** [comment]
@eason9487 Made some deeper investigation, and managed to work around it on our end by downgrading `@woocommerce/date@3.9.0` However, he got closer to the root cause than I did:


> I think that should be the root cause. But it needs much more time to investigate how to fix it without unexpected effects
> - The result of `get( target, [ 'file', 'request' ] ) === targetName` condition is always `false` at here https://github.com/woocommerce/woocommerce-admin/blob/v2.1.2/bin/packages/get-babel-config.js#L16
> - `modules` would never be set to `'commonjs'` at here https://github.com/woocommerce/woocommerce-admin/blob/v2.1.2/bin/packages/get-babel-config.js#L26-L28

**Comment by tomalec** [comment]
It's still an issue with WooCommerce 5.7 => `@woocommerce/components` 8.0.0 => 7.1.0 (8.0.0 is unpublished, so we need to fall back to 7.1.0.)

**Comment by chihsuan** [comment]
I was able to reproduce this with `@woocommerce/component` 8.1.1. I'm going to put this other backlog since I think this is more like a bug, not a feature request.

**Comment by chihsuan** [comment]
Hey @tomalec just wanted to let you know that the `@woocommerce/*` packages have included `commonjs` modules outputs, but we still need to include `moment-timezone` into our `@woocommerce/components` dependencies to fix `TypeError: Cannot read property 'add' of undefined`. I've opened a PR for it.

I've verified it works by updating dependencies in package.json to the latest:

```json
	"dependencies": {
		"@woocommerce/components": "^9.0.0",
		"@woocommerce/date": "^4.0.0",
		"@woocommerce/navigation": "^7.0.0",
		"@wordpress/date": "^4.3.1"
	}
```

Then, run the following commands:

```bash
cd node_modules/@woocommerce/components
npm install moment-timezone
cd ../../../
npm run test-unit
```

![Screen Shot 2022-03-11 at 14 06 19](https://user-images.githubusercontent.com/4344253/157812143-5ea04739-22d5-4429-b6d9-58e64cb4e847.png)

I also verified we can import the latest `@woocommerce/date` without errors.
