### ISSUE TITLE
Heads Up: Marketing > Coupons broken on Version 2.2.4

### ISSUE THREAD

**Issue by inpresif** [woocommerce/woocommerce-admin#6954]
Upgraded to Version 2.2.4 just now and the Marketing>Coupons link was broken/ Errored out

Deactivated this plugin and it's fine again.

Error logfile:

[Fri May 07 08:22:45.557580 2021] [proxy_fcgi:error] [pid 19381] [client 86.88.134.150:0] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Automattic\\WooCommerce\\Admin\\Loader::get_script_asset_filename(), 1 passed in /home/.../public_html/wp-content/plugins/woocommerce-admin/src/Features/Coupons.php on line 132 and exactly 2 expected in /home/.../public_html/wp-content/plugins/woocommerce-admin/src/Loader.php:255\nStack trace:\n#0 /home/.../public_html/wp-content/plugins/woocommerce-admin/src/Features/Coupons.php(132): Automattic\\WooCommerce\\Admin\\Loader::get_script_asset_filename('marketing-coupo...')\n#1 /home/.../public_html/wp-includes/class-wp-hook.php(292): Automattic\\WooCommerce\\Admin\\Features\\Coupons->maybe_add_marketing_coupon_script('edit.php')\n#2 /home/.../public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)\n#3 /home/.../pub...', referer: https://.../wp-admin/admin.php?page=wc-admin&path=%2Fmarketing

HTH.

**Comment by louwie17** [comment]
Thanks for creating an issue for this @inpresif, we have a fix ready (https://github.com/woocommerce/woocommerce-admin/pull/6955) and hope to do a release shortly after.
