### ISSUE TITLE
Docs generator failing due to babel typescript preset

### ISSUE THREAD

**Issue by ilyasfoo** [woocommerce/woocommerce-admin#7065]
**Describe the bug**
Docs generator `bin/generate-docs/index.js` errors out when it attempts to generate docs. I've noticed this when we run `npm run pre-release` as it gets run in this script.

A sample error:
```
docker/wordpress/wp-content/plugins/woocommerce-admin/packages/components/src/badge/index.js Error: [BABEL] unknown: Preset /* your preset */ requires a filename to be set when babel is called directly,
``
babel.transform(code, { filename: 'file.ts', presets: [/* your preset */] });
``
See https://babeljs.io/docs/en/options#filename for more information.
    at validateIfOptionNeedsFilename (docker/wordpress/wp-content/plugins/woocommerce-admin/node_modules/@babel/core/lib/config/full.js:291:11)
    at docker/wordpress/wp-content/plugins/woocommerce-admin/node_modules/@babel/core/lib/config/full.js:303:52
    at Array.forEach (<anonymous>)
    at validatePreset (docker/wordpress/wp-content/plugins/woocommerce-admin/node_modules/@babel/core/lib/config/full.js:303:25)
    at loadPresetDescriptor (docker/wordpress/wp-content/plugins/woocommerce-admin/node_modules/@babel/core/lib/config/full.js:310:3)
    at loadPresetDescriptor.next (<anonymous>)
    at recursePresetDescriptors (docker/wordpress/wp-content/plugins/woocommerce-admin/node_modules/@babel/core/lib/config/full.js:113:30)
    at recursePresetDescriptors.next (<anonymous>)
    at docker/wordpress/wp-content/plugins/woocommerce-admin/node_modules/@babel/core/lib/config/full.js:187:21
    at Generator.next (<anonymous>)
```

**To Reproduce**

1. Make sure you have a new component that does not have docs - as of 2.3.1 we have `docs/components/packages/badge/index.js`
2. Run `node ./bin/generate-docs/index.js`
2. Observe the error.

**Expected behavior**
No error.

**Additional context**
As I investigated a little bit further, it seems that the inclusion of `'@babel/preset-typescript'` in our `babel.config.js` may have something to do with this.

**Comment by samueljseay** [comment]
fwiw the plan is to ditch the legacy docs. See https://github.com/woocommerce/woocommerce-admin/issues/6098

**Comment by ilyasfoo** [comment]
That's def a better path forward. Closing this in favour of #6098
