### ISSUE TITLE
Uncaught Error: Class 'Automattic\WooCommerce\Admin\API\OnboardingPlugins' not found in /usr/share/nginx/html/wp-store/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/InstallJPAndWCSPlugins.php:114

### ISSUE THREAD

**Issue by blipk** [woocommerce/woocommerce-admin#7583]
Installed woocommerce on a fresh wordpress installation via the plugins installer, get the following error when trying to install any of the plugins via woocommerce in the setup wizard, jetpack, mailchimp etc.

```
2021-08-29T05:38:46+00:00 CRITICAL Uncaught Error: Class 'Automattic\WooCommerce\Admin\API\OnboardingPlugins' not found in /usr/share/nginx/html/wp-store/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/InstallJPAndWCSPlugins.php:114
Stack trace:
#0 /usr/share/nginx/html/wp-store/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/InstallJPAndWCSPlugins.php(103): Automattic\WooCommerce\Admin\Notes\InstallJPAndWCSPlugins->install_and_activate_plugin('jetpack')
#1 /usr/share/nginx/html/wp-store/wp-includes/class-wp-hook.php(303): Automattic\WooCommerce\Admin\Notes\InstallJPAndWCSPlugins->install_jp_and_wcs_plugins(Object(Automattic\WooCommerce\Admin\Notes\Note))
#2 /usr/share/nginx/html/wp-store/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#3 /usr/share/nginx/html/wp-store/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#4 /usr/share/nginx/html/wp-store/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/Notes.php(346): do_action('woocommerce_not...', Object(Autom in /usr/share/nginx/html/wp-store/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/InstallJPAndWCSPlugins.php on line 114
```

**Comment by ilyasfoo** [comment]
Hi, @blipk! Thank you for taking the time to report this issue. I have tried to reproduce by installing the latest WooCommerce via the plugins installer, however unable to do so.

If it's not too much, are you able to you share the version of WordPress and PHP that you're getting this on? I have tested this on WordPress 5.8 and PHP 7.4.22.
