### ISSUE TITLE
Package-lock.json is incompatible with npm 7+

### ISSUE THREAD

**Issue by Mte90** [woocommerce/woocommerce-admin#7701]
_**Update: The root cause of this issue is that our `package-lock.json` file is incompatible with npm 7+. See #7932 for a partial fix (it sets Node to 14, which includes npm 6). - @mattsherman**_

### Describe the bug
I am trying to follow https://developer.woocommerce.com/2020/02/20/extending-wc-admin-reports/ this guide but I am facing those errors:
PS: the guide is missing a `npm install` after downloading the repo.

### To Reproduce
```
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN old lockfile Error: Integrity checksum failed when using sha512: wanted sha512-mqAC2r1NDmRjG+z3KCJ/i61tycKlmADIjxnDhQab+KBxSAGbF/W7/zwB2guy/ypIeKrrftNsIYkNZZQKf3vJcg== but got sha512-s7PoyDv/II1ObgQunCbB9PdLmUcBZcnWOcxDh7O0N/UwDEsHyqkW+Qh28jW+mVuCdx7gLB0BotYI1Y6uI9iyew==.
npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:145:39
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:717:9)
npm WARN old lockfile  Could not fetch metadata for prettier@1.19.1 Error: Integrity checksum failed when using sha512: wanted sha512-mqAC2r1NDmRjG+z3KCJ/i61tycKlmADIjxnDhQab+KBxSAGbF/W7/zwB2guy/ypIeKrrftNsIYkNZZQKf3vJcg== but got sha512-s7PoyDv/II1ObgQunCbB9PdLmUcBZcnWOcxDh7O0N/UwDEsHyqkW+Qh28jW+mVuCdx7gLB0BotYI1Y6uI9iyew==.
npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:145:39
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:717:9) {
npm WARN old lockfile   code: 'EINTEGRITY'
npm WARN old lockfile }
npm WARN old lockfile Error: git dep preparation failed
npm WARN old lockfile     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
npm WARN old lockfile     at ChildProcess.emit (events.js:314:20)
npm WARN old lockfile     at maybeClose (internal/child_process.js:1022:16)
npm WARN old lockfile     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
npm WARN old lockfile  Could not fetch metadata for @automattic/puppeteer-utils@git+ssh://git@github.com/Automattic/puppeteer-utils.git#0f3ec50fc22d7bd2a4bd69fc172e8a66d958ef2d Error: git dep preparation failed
npm WARN old lockfile     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
npm WARN old lockfile     at ChildProcess.emit (events.js:314:20)
npm WARN old lockfile     at maybeClose (internal/child_process.js:1022:16)
npm WARN old lockfile     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
npm WARN old lockfile   cmd: '/usr/bin/node',
npm WARN old lockfile   args: [
npm WARN old lockfile     '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
npm WARN old lockfile     'install',
npm WARN old lockfile     '--force',
npm WARN old lockfile     '--cache=/home/mte90/.npm',
npm WARN old lockfile     '--prefer-offline=false',
npm WARN old lockfile     '--prefer-online=false',
npm WARN old lockfile     '--offline=false',
npm WARN old lockfile     '--no-progress',
npm WARN old lockfile     '--no-save',
npm WARN old lockfile     '--no-audit',
npm WARN old lockfile     '--include=dev',
npm WARN old lockfile     '--include=peer',
npm WARN old lockfile     '--include=optional',
npm WARN old lockfile     '--no-package-lock-only',
npm WARN old lockfile     '--no-dry-run'
npm WARN old lockfile   ],
npm WARN old lockfile   code: 1,
npm WARN old lockfile   signal: null,
npm WARN old lockfile   stdout: '\n' +
npm WARN old lockfile     '> @automattic/puppeteer-utils@0.0.1 postinstall\n' +
npm WARN old lockfile     '> npm run build\n' +
npm WARN old lockfile     '\n' +
npm WARN old lockfile     '\n' +
npm WARN old lockfile     '> @automattic/puppeteer-utils@0.0.1 build\n' +
npm WARN old lockfile     '> babel --presets=@babel/preset-env src -d lib\n' +
npm WARN old lockfile     '\n',
npm WARN old lockfile   stderr: 'npm WARN using --force Recommended protections disabled.\n' +
npm WARN old lockfile     'npm WARN old lockfile \n' +
npm WARN old lockfile     'npm WARN old lockfile The package-lock.json file was created with an old version of npm,\n' +
npm WARN old lockfile     'npm WARN old lockfile so supplemental metadata must be fetched from the registry.\n' +
npm WARN old lockfile     'npm WARN old lockfile \n' +
npm WARN old lockfile     'npm WARN old lockfile This is a one-time fix-up, please be patient...\n' +
npm WARN old lockfile     'npm WARN old lockfile \n' +
npm WARN old lockfile     'npm WARN old lockfile Error: Integrity checksum failed when using sha512: wanted sha512-mqAC2r1NDmRjG+z3KCJ/i61tycKlmADIjxnDhQab+KBxSAGbF/W7/zwB2guy/ypIeKrrftNsIYkNZZQKf3vJcg== but got sha512-s7PoyDv/II1ObgQunCbB9PdLmUcBZcnWOcxDh7O0N/UwDEsHyqkW+Qh28jW+mVuCdx7gLB0BotYI1Y6uI9iyew==.\n' +
npm WARN old lockfile     'npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:145:39\n' +
npm WARN old lockfile     'npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:717:9)\n' +
npm WARN old lockfile     'npm WARN old lockfile  Could not fetch metadata for prettier@1.19.1 Error: Integrity checksum failed when using sha512: wanted sha512-mqAC2r1NDmRjG+z3KCJ/i61tycKlmADIjxnDhQab+KBxSAGbF/W7/zwB2guy/ypIeKrrftNsIYkNZZQKf3vJcg== but got sha512-s7PoyDv/II1ObgQunCbB9PdLmUcBZcnWOcxDh7O0N/UwDEsHyqkW+Qh28jW+mVuCdx7gLB0BotYI1Y6uI9iyew==.\n' +
npm WARN old lockfile     'npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:145:39\n' +
npm WARN old lockfile     'npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:717:9) {\n' +
npm WARN old lockfile     "npm WARN old lockfile   code: 'EINTEGRITY'\n" +
npm WARN old lockfile     'npm WARN old lockfile }\n' +
npm WARN old lockfile     'npm WARN deprecated request-promise-native@1.0.8: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142\n' +
npm WARN old lockfile     'npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated\n' +
npm WARN old lockfile     'npm WARN deprecated har-validator@5.1.3: this library is no longer supported\n' +
npm WARN old lockfile     'npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated\n' +
npm WARN old lockfile     'npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()\n' +
npm WARN old lockfile     'npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added\n' +
npm WARN old lockfile     'npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)\n' +
npm WARN old lockfile     'npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)\n' +
npm WARN old lockfile     'npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.\n' +
npm WARN old lockfile     'npm WARN deprecated uuid@3.3.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.\n' +
npm WARN old lockfile     'npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)\n' +
npm WARN old lockfile     'npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142\n' +
npm WARN old lockfile     'npm WARN deprecated axios@0.18.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410\n' +
npm WARN old lockfile     'npm WARN using --force Recommended protections disabled.\n' +
npm WARN old lockfile     'Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/mte90/.npm/_cacache/tmp/git-cloneFtXYj6/node_modules/@babel/helper-compilation-targets/package.json\n' +
npm WARN old lockfile     '    at throwExportsNotFound (internal/modules/esm/resolve.js:299:9)\n' +
npm WARN old lockfile     '    at packageExportsResolve (internal/modules/esm/resolve.js:522:3)\n' +
npm WARN old lockfile     '    at resolveExports (internal/modules/cjs/loader.js:424:36)\n' +
npm WARN old lockfile     '    at Function.Module._findPath (internal/modules/cjs/loader.js:464:31)\n' +
npm WARN old lockfile     '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)\n' +
npm WARN old lockfile     '    at Function.Module._load (internal/modules/cjs/loader.js:667:27)\n' +
npm WARN old lockfile     '    at Module.require (internal/modules/cjs/loader.js:887:19)\n' +
npm WARN old lockfile     '    at require (internal/modules/cjs/helpers.js:74:18)\n' +
npm WARN old lockfile     '    at Object.<anonymous> (/home/mte90/.npm/_cacache/tmp/git-cloneFtXYj6/node_modules/@babel/preset-env/lib/debug.js:8:33)\n' +
npm WARN old lockfile     '    at Module._compile (internal/modules/cjs/loader.js:999:30) {\n' +
npm WARN old lockfile     "  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'\n" +
npm WARN old lockfile     '}\n' +
npm WARN old lockfile     'npm ERR! code 1\n' +
npm WARN old lockfile     'npm ERR! path /home/mte90/.npm/_cacache/tmp/git-cloneFtXYj6\n' +
npm WARN old lockfile     'npm ERR! command failed\n' +
npm WARN old lockfile     'npm ERR! command sh -c npm run build\n' +
npm WARN old lockfile     '\n' +
npm WARN old lockfile     'npm ERR! A complete log of this run can be found in:\n' +
npm WARN old lockfile     'npm ERR!     /home/mte90/.npm/_logs/2021-09-23T14_18_23_047Z-debug.log\n'
npm WARN old lockfile }
npm WARN old lockfile components: No matching version found for components@8.1.0.
npm WARN old lockfile     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:717:9)
npm WARN old lockfile  Could not fetch metadata for components@8.1.0 components: No matching version found for components@8.1.0.
npm WARN old lockfile     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:717:9) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '8.1.0',
npm WARN old lockfile   versions: [ '0.0.0', '0.1.0' ],
npm WARN old lockfile   distTags: { latest: '0.1.0' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm WARN old lockfile HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/admin-e2e-tests - Not found
npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
npm WARN old lockfile     at runMicrotasks (<anonymous>)
npm WARN old lockfile     at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:717:9)
npm WARN old lockfile  Could not fetch metadata for admin-e2e-tests@0.1.1 HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/admin-e2e-tests - Not found
npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
npm WARN old lockfile     at runMicrotasks (<anonymous>)
npm WARN old lockfile     at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:717:9) {
npm WARN old lockfile   headers: [Object: null prototype] {
npm WARN old lockfile     date: [ 'Thu, 23 Sep 2021 14:18:58 GMT' ],
npm WARN old lockfile     'content-type': [ 'application/json' ],
npm WARN old lockfile     'content-length': [ '21' ],
npm WARN old lockfile     connection: [ 'keep-alive' ],
npm WARN old lockfile     'cf-ray': [ '693467c51bb4cd2a-FCO' ],
npm WARN old lockfile     age: [ '254' ],
npm WARN old lockfile     vary: [ 'Accept-Encoding' ],
npm WARN old lockfile     'expect-ct': [
npm WARN old lockfile       'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"'
npm WARN old lockfile     ],
npm WARN old lockfile     server: [ 'cloudflare' ],
npm WARN old lockfile     'x-fetch-attempts': [ '1' ],
npm WARN old lockfile     'x-local-cache-status': [ 'skip' ]
npm WARN old lockfile   },
npm WARN old lockfile   statusCode: 404,
npm WARN old lockfile   code: 'E404',
npm WARN old lockfile   method: 'GET',
npm WARN old lockfile   uri: 'https://registry.npmjs.org/admin-e2e-tests',
npm WARN old lockfile   body: { error: 'Not found' },
npm WARN old lockfile   pkgid: 'admin-e2e-tests@0.1.1'
npm WARN old lockfile }
npm WARN old lockfile csv-export: No matching version found for csv-export@1.4.0.
npm WARN old lockfile     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:717:9)
npm WARN old lockfile  Could not fetch metadata for csv-export@1.4.0 csv-export: No matching version found for csv-export@1.4.0.
npm WARN old lockfile     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:717:9) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '1.4.0',
npm WARN old lockfile   versions: [ '1.0.0', '1.0.1', '1.0.2' ],
npm WARN old lockfile   distTags: { latest: '1.0.2' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm WARN old lockfile currency: No matching version found for currency@3.2.0.
npm WARN old lockfile     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:717:9)
npm WARN old lockfile  Could not fetch metadata for currency@3.2.0 currency: No matching version found for currency@3.2.0.
npm WARN old lockfile     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:717:9) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '3.2.0',
npm WARN old lockfile   versions: [
npm WARN old lockfile     '0.0.1', '0.0.2',
npm WARN old lockfile     '0.0.3', '0.0.4',
npm WARN old lockfile     '0.0.5', '0.1.0',
npm WARN old lockfile     '0.1.1', '0.1.2',
npm WARN old lockfile     '1.0.0', '1.0.1',
npm WARN old lockfile     '2.0.0', '3.0.0',
npm WARN old lockfile     '4.0.0', '4.1.0'
npm WARN old lockfile   ],
npm WARN old lockfile   distTags: { latest: '4.1.0' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm ERR! Tracker "idealTree:inflate:" already exists
```

**Comment by louwie17** [comment]
Hi @Mte90 thanks for creating an issue for this.
What node version are you using, I only encounter this error when I run the latest (non LTS) version `16.10`, when I use the latest stable version - `14.17.6` it installs and builds fine.
Let me know if you do encounter this with a stable version of `node`?

**Comment by Mte90** [comment]
I am using node 12 on debian

**Comment by louwie17** [comment]
> I am using node 12 on debian

Thanks, which version of 12 are you using on debian? I tried it on debian with the latest version `12.22.6` and things worked fine. I also tried it with 12.18 & 12.20, which both worked fine.

**Comment by Mte90** [comment]
v12.22.5 😅 from their unstable repositories.

**Comment by joshuatf** [comment]
@Mte90 can you try running `npm cache verify` and `npm cache clean --force` before installing again?  Also, was this on a fresh clone of this repository?

**Comment by Mte90** [comment]
this was on a clone of this repository, I tried now those commands and nothing changed always errors.

**Comment by louwie17** [comment]
> this was on a clone of this repository, I tried now those commands and nothing changed always errors.

That is not great, I am starting to run out of idea's on what this could be.
@joelclimbsthings I believe you are running linux right? are you able to reproduce this?

**Comment by joelclimbsthings** [comment]
Nope @louwie17 , not able to reproduce on my end. I'm running PopOS (based on Ubuntu), and also ran the above on `v12.22.5` without an issue.

**Comment by Mte90** [comment]
I am using npm 7.24.0 if could be helpful on understand what is wrong.

**Comment by mattsherman** [comment]
I hit this same issue last night when setting up a new dev environment, as the latest LTS version of Node is now 16 (which includes npm 8). See #7932 for a partial fix.
