### ISSUE TITLE
Update JS Dependencies for WooCommerce 6.4

### ISSUE THREAD

**Issue by adrianduffell** [woocommerce/woocommerce-admin#8344]
I'd like to align updating our JS dependencies with the Core release cycle.

As a low risk first step, for the 6.4 cycle, I think we could update all packages with minor/patch version changes.

For packages with major version changes, we could create new issues to help focus on the fixes needed for any breaking changes. We'd then prioritize those in the 6.5 cycle and beyond. 

### Questions

- Where did Renovatebot go? This bot used to be in place to update dependencies.
- Could dependabot help this task? 

### Output for `npm outdated`
```
% npm outdated
Package                                           Current    Wanted    Latest  Location
@automattic/explat-client                           0.0.2     0.0.2     0.0.3  @woocommerce/admin-library
@babel/cli                                        7.13.16   7.13.16    7.17.6  @woocommerce/admin-library
@babel/core                                        7.14.0    7.14.0    7.17.5  @woocommerce/admin-library
@babel/plugin-proposal-class-properties            7.14.5    7.14.5    7.16.7  @woocommerce/admin-library
@babel/plugin-transform-react-jsx                 7.13.12   7.13.12    7.17.3  @woocommerce/admin-library
@babel/preset-env                                  7.14.1    7.14.1   7.16.11  @woocommerce/admin-library
@babel/preset-typescript                           7.13.0    7.13.0    7.16.7  @woocommerce/admin-library
@storybook/addon-a11y                               6.2.9     6.2.9    6.4.19  @woocommerce/admin-library
@storybook/addon-actions                            6.2.9     6.2.9    6.4.19  @woocommerce/admin-library
@storybook/addon-docs                               6.2.9     6.2.9    6.4.19  @woocommerce/admin-library
@storybook/addon-knobs                              6.2.9     6.2.9     6.4.0  @woocommerce/admin-library
@storybook/addon-links                              6.2.9     6.2.9    6.4.19  @woocommerce/admin-library
@storybook/addon-storysource                        6.2.9     6.2.9    6.4.19  @woocommerce/admin-library
@storybook/addon-viewport                           6.2.9     6.2.9    6.4.19  @woocommerce/admin-library
@storybook/addons                                   6.2.9     6.2.9    6.4.19  @woocommerce/admin-library
@storybook/react                                    6.2.9     6.2.9    6.4.19  @woocommerce/admin-library
@testing-library/jest-dom                          5.14.0    5.14.0    5.16.2  @woocommerce/admin-library
@testing-library/react                             12.0.0    12.0.0    12.1.3  @woocommerce/admin-library
@testing-library/react-hooks                        7.0.1     7.0.1     7.0.2  @woocommerce/admin-library
@testing-library/user-event                        13.2.1    13.2.1    13.5.0  @woocommerce/admin-library
@types/dompurify                                    2.2.2     2.2.2     2.3.3  @woocommerce/admin-library
@types/expect-puppeteer                             4.4.6     4.4.6     4.4.7  @woocommerce/admin-library
@types/history                                      4.7.8     4.7.8     5.0.0  @woocommerce/admin-library
@types/jest                                       26.0.23   26.0.23    27.4.0  @woocommerce/admin-library
@types/lodash                                    4.14.170  4.14.170  4.14.178  @woocommerce/admin-library
@types/puppeteer                                    4.0.1     4.0.1     5.4.4  @woocommerce/admin-library
@types/react-router-dom                             5.1.7     5.1.7     5.3.3  @woocommerce/admin-library
@types/react-transition-group                       4.4.1     4.4.1     4.4.4  @woocommerce/admin-library
@typescript-eslint/eslint-plugin                   4.22.1    4.22.1    5.12.1  @woocommerce/admin-library
@woocommerce/e2e-environment                        0.2.3     0.2.3     0.3.0  @woocommerce/admin-library
@woocommerce/e2e-utils                              0.1.6     0.1.6     0.2.0  @woocommerce/admin-library
@wordpress/babel-plugin-makepot                     2.1.3     2.1.3     4.2.1  @woocommerce/admin-library
@wordpress/base-styles                              3.3.0     3.3.0     4.1.1  @woocommerce/admin-library
@wordpress/browserslist-config                      4.0.1     4.0.1     4.1.1  @woocommerce/admin-library
@wordpress/core-data                                4.1.0     4.1.0     4.1.1  @woocommerce/admin-library
@wordpress/custom-templated-path-webpack-plugin     1.7.0     1.7.0     2.1.1  @woocommerce/admin-library
@wordpress/e2e-test-utils                          4.16.1    4.16.1     6.0.1  @woocommerce/admin-library
@wordpress/eslint-plugin                            8.0.0     8.0.0    10.0.1  @woocommerce/admin-library
@wordpress/hooks                                   2.11.0    2.11.0     3.3.1  @woocommerce/admin-library
@wordpress/jest-preset-default                      8.0.0     8.0.0     8.0.1  @woocommerce/admin-library
@wordpress/notices                                  3.3.0     3.3.0     3.3.1  @woocommerce/admin-library
@wordpress/plugins                                  4.1.0     4.1.0     4.1.1  @woocommerce/admin-library
@wordpress/postcss-plugins-preset                   1.6.0     1.6.0     3.3.1  @woocommerce/admin-library
@wordpress/postcss-themes                           1.0.5     1.0.5     4.2.1  @woocommerce/admin-library
@wordpress/prettier-config                          0.4.0     0.4.0     1.1.2  @woocommerce/admin-library
@wordpress/scripts                                 12.6.1    12.6.1    22.0.0  @woocommerce/admin-library
@wordpress/viewport                                 4.1.0     4.1.0     4.1.1  @woocommerce/admin-library
autoprefixer                                       10.2.6    10.2.6    10.4.2  @woocommerce/admin-library
babel-jest                                         26.6.3    26.6.3    27.5.1  @woocommerce/admin-library
babel-loader                                        8.2.2     8.2.2     8.2.3  @woocommerce/admin-library
chalk                                               4.1.1     4.1.1     5.0.0  @woocommerce/admin-library
comment-parser                                      1.1.5     1.1.5     1.3.0  @woocommerce/admin-library
concurrently                                        5.3.0     5.3.0     7.0.0  @woocommerce/admin-library
config                                              3.3.6     3.3.6     3.3.7  @woocommerce/admin-library
copy-webpack-plugin                                 5.1.2     5.1.2    10.2.4  @woocommerce/admin-library
core-js                                             3.9.1     3.9.1    3.21.1  @woocommerce/admin-library
css-loader                                          3.6.0     3.6.0     6.6.0  @woocommerce/admin-library
debug                                               4.3.1     4.3.1     4.3.3  @woocommerce/admin-library
dompurify                                           2.2.9     2.2.9     2.3.6  @woocommerce/admin-library
eslint-import-resolver-typescript                   2.4.0     2.4.0     2.5.0  @woocommerce/admin-library
eslint-import-resolver-webpack                     0.13.1    0.13.1    0.13.2  @woocommerce/admin-library
eslint-plugin-import                               2.22.1    2.22.1    2.25.4  @woocommerce/admin-library
eslint-plugin-react                                7.24.0    7.24.0    7.28.0  @woocommerce/admin-library
fork-ts-checker-webpack-plugin                     6.2.10    6.2.10     7.2.1  @woocommerce/admin-library
fs-extra                                            8.1.0     8.1.0    10.0.0  @woocommerce/admin-library
github-label-sync                                   2.0.0     2.0.0     2.0.2  @woocommerce/admin-library
grunt                                               1.3.0     1.3.0     1.4.1  @woocommerce/admin-library
husky                                               4.3.8     4.3.8     7.0.4  @woocommerce/admin-library
jest                                               27.0.6    27.0.6    27.5.1  @woocommerce/admin-library
jest-environment-jsdom                             27.0.6    27.0.6    27.5.1  @woocommerce/admin-library
lerna                                              3.22.1    3.22.1     4.0.0  @woocommerce/admin-library
lint-staged                                        10.5.4    10.5.4    12.3.4  @woocommerce/admin-library
memoize-one                                         5.1.1     5.1.1     6.0.0  @woocommerce/admin-library
moment-timezone-data-webpack-plugin                 1.3.0     1.3.0     1.5.0  @woocommerce/admin-library
node-watch                                          0.7.1     0.7.1     0.7.3  @woocommerce/admin-library
postcss-loader                                      3.0.0     3.0.0     6.2.1  @woocommerce/admin-library
prop-types                                         15.7.2    15.7.2    15.8.1  @woocommerce/admin-library
qs                                                  6.9.6     6.9.6    6.10.3  @woocommerce/admin-library
react-dates                                        17.2.0    17.2.0    21.8.0  @woocommerce/admin-library
react-router-dom                                    5.2.0     5.2.0     6.2.1  @woocommerce/admin-library
react-transition-group                              4.4.1     4.4.1     4.4.2  @woocommerce/admin-library
rtlcss                                              2.5.0     2.5.0     3.5.0  @woocommerce/admin-library
sass                                               1.34.0    1.34.0    1.49.8  @woocommerce/admin-library
sass-loader                                        10.1.1    10.1.1    12.6.0  @woocommerce/admin-library
style-loader                                       0.23.1    0.23.1     3.3.1  @woocommerce/admin-library
stylelint                                          9.10.1    9.10.1    14.5.1  @woocommerce/admin-library
stylelint-config-wordpress                         13.1.0    13.1.0    17.0.0  @woocommerce/admin-library
terser-webpack-plugin                               2.3.8     2.3.8     5.3.1  @woocommerce/admin-library
ts-jest                                            27.0.4    27.0.4    27.1.3  @woocommerce/admin-library
typescript                                          4.2.4     4.2.4     4.5.5  @woocommerce/admin-library
url-loader                                          1.1.2     1.1.2     4.1.1  @woocommerce/admin-library
webpack                                            4.43.0    4.43.0    5.69.1  @woocommerce/admin-library
webpack-bundle-analyzer                             3.6.1     3.6.1     4.5.0  @woocommerce/admin-library
webpack-cli                                        3.3.12    3.3.12     4.9.2  @woocommerce/admin-library
```

**Comment by chihsuan** [comment]
> Where did Renovatebot go? This bot used to be in place to update dependencies.
    
Looks like Renovate bot is trying to do its work but failed.

![Screen Shot 2022-03-01 at 14 23 08](https://user-images.githubusercontent.com/4344253/156116328-bd300256-3775-4257-a037-454eb39f3cc5.png)

```
{
  "err": {
    "killed": true,
    "code": null,
    "signal": "SIGTERM",
    "cmd": "docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/woocommerce/woocommerce-admin\":\"/mnt/renovate/gh/woocommerce/woocommerce-admin\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -w \"/mnt/renovate/gh/woocommerce/woocommerce-admin\" docker.io/renovate/node:14.19.0 bash -l -c \"npm i -g npm@'>=6.14.10 <7 <7' || true && hash -d npm 2>/dev/null || true && npm i -g lerna@3.22.1 && lerna info || echo \\\"Ignoring lerna info failure\\\" && npm install --ignore-scripts  --no-audit && lerna bootstrap --no-ci --ignore-scripts -- --ignore-scripts  --no-audit\"",
    "stdout": "/home/ubuntu/.npm-global/bin/npm -> /home/ubuntu/.npm-global/lib/node_modules/npm/bin/npm-cli.js\n/home/ubuntu/.npm-global/bin/npx -> /home/ubuntu/.npm-global/lib/node_modules/npm/bin/npx-cli.js\n+ npm@6.14.16\nadded 437 packages from 891 contributors in 53.378s\n/home/ubuntu/.npm-global/bin/lerna -> /home/ubuntu/.npm-global/lib/node_modules/lerna/cli.js\n+ lerna@3.22.1\nadded 788 packages from 386 contributors in 74.931s\n\n Environment info:\n\n  System:\n    OS: Linux 4.15 Ubuntu 20.04.3 LTS (Focal Fossa)\n    CPU: (1) x64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz\n  Binaries:\n    Node: 14.19.0 - /usr/local/bin/node\n    npm: 6.14.16 - ~/.npm-global/bin/npm\n  Utilities:\n    Git: 2.35.1 - /usr/bin/git\n\nadded 4856 packages from 1568 contributors in 450.871s\n\n354 packages are looking for funding\n  run `npm fund` for details\n\n",
    "stderr": "npm WARN deprecated read-package-tree@5.3.1: The functionality that this package provided is now in @npmcli/arborist\nnpm WARN deprecated source-map-resolve@0.5.3: See https://**redacted**@0.1.0: Please see https://**redacted**@0.4.1: See https://**redacted**@0.2.1: https://**redacted**@2.88.2: request has been deprecated, see https://**redacted**@5.1.5: this library is no longer supported\nnpm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://**redacted**@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.\nnpm WARN @octokit/plugin-request-log@1.0.4 requires a peer of @octokit/core@>=3 but none is installed. You must install peer dependencies yourself.\n\nlerna notice cli v3.22.1\nlerna info versioning independent\nnpm WARN react-docgen-typescript@2.2.2 requires a peer of typescript@>= 4.3.x but none is installed. You must install peer dependencies yourself.\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {\"os\":\"darwin\",\"arch\":\"any\"} (current: {\"os\":\"linux\",\"arch\":\"x64\"})\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/jest-haste-map/node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {\"os\":\"darwin\",\"arch\":\"any\"} (current: {\"os\":\"linux\",\"arch\":\"x64\"})\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {\"os\":\"darwin\",\"arch\":\"any\"} (current: {\"os\":\"linux\",\"arch\":\"x64\"})\n\ninfo cli using local version of lerna\nlerna notice cli v3.22.1\nlerna info versioning independent\nlerna info Bootstrapping 18 packages\nlerna info Installing external dependencies\n",
    "message": "Command failed: docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/woocommerce/woocommerce-admin\":\"/mnt/renovate/gh/woocommerce/woocommerce-admin\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -w \"/mnt/renovate/gh/woocommerce/woocommerce-admin\" docker.io/renovate/node:14.19.0 bash -l -c \"npm i -g npm@'>=6.14.10 <7 <7' || true && hash -d npm 2>/dev/null || true && npm i -g lerna@3.22.1 && lerna info || echo \\\"Ignoring lerna info failure\\\" && npm install --ignore-scripts  --no-audit && lerna bootstrap --no-ci --ignore-scripts -- --ignore-scripts  --no-audit\"\nnpm WARN deprecated read-package-tree@5.3.1: The functionality that this package provided is now in @npmcli/arborist\nnpm WARN deprecated source-map-resolve@0.5.3: See https://**redacted**@0.1.0: Please see https://**redacted**@0.4.1: See https://**redacted**@0.2.1: https://**redacted**@2.88.2: request has been deprecated, see https://**redacted**@5.1.5: this library is no longer supported\nnpm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://**redacted**@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.\nnpm WARN @octokit/plugin-request-log@1.0.4 requires a peer of @octokit/core@>=3 but none is installed. You must install peer dependencies yourself.\n\nlerna notice cli v3.22.1\nlerna info versioning independent\nnpm WARN react-docgen-typescript@2.2.2 requires a peer of typescript@>= 4.3.x but none is installed. You must install peer dependencies yourself.\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {\"os\":\"darwin\",\"arch\":\"any\"} (current: {\"os\":\"linux\",\"arch\":\"x64\"})\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/jest-haste-map/node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {\"os\":\"darwin\",\"arch\":\"any\"} (current: {\"os\":\"linux\",\"arch\":\"x64\"})\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {\"os\":\"darwin\",\"arch\":\"any\"} (current: {\"os\":\"linux\",\"arch\":\"x64\"})\n\ninfo cli using local version of lerna\nlerna notice cli v3.22.1\nlerna info versioning independent\nlerna info Bootstrapping 18 packages\nlerna info Installing external dependencies\n",
    "stack": "Error: Command failed: docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/woocommerce/woocommerce-admin\":\"/mnt/renovate/gh/woocommerce/woocommerce-admin\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -w \"/mnt/renovate/gh/woocommerce/woocommerce-admin\" docker.io/renovate/node:14.19.0 bash -l -c \"npm i -g npm@'>=6.14.10 <7 <7' || true && hash -d npm 2>/dev/null || true && npm i -g lerna@3.22.1 && lerna info || echo \\\"Ignoring lerna info failure\\\" && npm install --ignore-scripts  --no-audit && lerna bootstrap --no-ci --ignore-scripts -- --ignore-scripts  --no-audit\"\nnpm WARN deprecated read-package-tree@5.3.1: The functionality that this package provided is now in @npmcli/arborist\nnpm WARN deprecated source-map-resolve@0.5.3: See https://**redacted**@0.1.0: Please see https://**redacted**@0.4.1: See https://**redacted**@0.2.1: https://**redacted**@2.88.2: request has been deprecated, see https://**redacted**@5.1.5: this library is no longer supported\nnpm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://**redacted**@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.\nnpm WARN @octokit/plugin-request-log@1.0.4 requires a peer of @octokit/core@>=3 but none is installed. You must install peer dependencies yourself.\n\nlerna notice cli v3.22.1\nlerna info versioning independent\nnpm WARN react-docgen-typescript@2.2.2 requires a peer of typescript@>= 4.3.x but none is installed. You must install peer dependencies yourself.\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {\"os\":\"darwin\",\"arch\":\"any\"} (current: {\"os\":\"linux\",\"arch\":\"x64\"})\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/jest-haste-map/node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {\"os\":\"darwin\",\"arch\":\"any\"} (current: {\"os\":\"linux\",\"arch\":\"x64\"})\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {\"os\":\"darwin\",\"arch\":\"any\"} (current: {\"os\":\"linux\",\"arch\":\"x64\"})\n\ninfo cli using local version of lerna\nlerna notice cli v3.22.1\nlerna info versioning independent\nlerna info Bootstrapping 18 packages\nlerna info Installing external dependencies\n\n    at ChildProcess.exithandler (child_process.js:383:12)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:475:12)\n    at maybeClose (internal/child_process.js:1058:16)\n    at Socket.<anonymous> (internal/child_process.js:443:11)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:475:12)\n    at Pipe.<anonymous> (net.js:686:12)"
  }
}
```

Possibly due to process timeouts. See this: https://github.com/renovatebot/renovate/issues/10769

But we also manually closed and delete the last Renovate-created branch https://github.com/woocommerce/woocommerce-admin/pull/7626#issuecomment-1055068099. I just unchecked the retry option. Let's see if it can work.

**Comment by chihsuan** [comment]
> Could dependabot help this task?

Yes, I think it can help. It also supports `pnpm`. 

I'll add `^` to our version numbers to accept minor/patch updates since we use the exact match version rule for many packages in `package.json`.

**Comment by chihsuan** [comment]
> Possibly due to process timeouts.

I believe this is the reason why the bot fails because it's killed during installing external dependencies without explicit errors. Unfortunately, I only find [`executionTimeout`](https://docs.renovatebot.com/self-hosted-configuration/#executiontimeout) option in the Self-hosted section but not [Repository](https://docs.renovatebot.com/configuration-options/).

I think we can wait and see if pnpm PR can fix Renovatebot.

**Comment by adrianduffell** [comment]
Just changed the title of this as these changes are now scheduled to land WooCommerce 6.5 due to the merge timeline.
